[package]
name = "runtime-luau"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-channel.workspace = true
base64 = "0.22"
experience-ir.workspace = true
experience-package.workspace = true
mlua = { version = "=0.12.0", default-features = false, features = ["luau", "serde"] }
naga = { version = "29.0.4", features = ["wgsl-in"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
providers-fake.workspace = true
serde.workspace = true
