[package]
name = "android-system-authority"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
android-authority-protocol.workspace = true
experience-ir.workspace = true
experience-package.workspace = true
libc = "0.2"
revision-supervisor = { path = "../revision-supervisor" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
android-provider-acceptance = { path = "../android-provider-acceptance" }
tempfile = "3"

[[bin]]
name = "sos-android-system-authority"
path = "src/main.rs"
